[project]
name = "lidartree"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "geopandas",
    "matplolib",
    "pandas",
    "rasterio",
    "shapely",
    "tifffile",
]
